spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: 8979704800
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update



server:
  port: 8081